fix: prevent undefined array key exception
DFAU/toujou-oauth2-server pull request #10
Opened 2023-03-10 13:38 UTC by helsner

2023-03-10 13:41 UTC, twojtylak requested changes
Warning: ] 3 errors are fixable! Just add "--fix" to console command and rerun  
           to apply.

2023-03-13 08:30 UTC, tmaroschik requested changes

2023-03-13 08:30 UTC, tmaroschik commented on Configuration/TCA/Overrides/be_users.php
> +if (isset($GLOBALS['SiteConfiguration']['site']['types']['0']['showitem'])
I think this whole if can be dropped, as this is duplicated here https://github.com/DFAU/toujou-oauth2-server/blob/master/Configuration/SiteConfiguration/Overrides/sites.php#L19

2023-03-13 09:30 UTC, helsner commented on Configuration/TCA/Overrides/be_users.php
> +if (isset($GLOBALS['SiteConfiguration']['site']['types']['0']['showitem'])
lmao, k will do
did not even realize, SiteConfig stuff makes no sense in the be_users TCA

2023-03-13 09:49 UTC, helsner commented on Configuration/TCA/Overrides/be_users.php
> +if (isset($GLOBALS['SiteConfiguration']['site']['types']['0']['showitem'])
updated

2023-03-14 14:15 UTC, merged